
const SIGNAL_CHARACTERS = [
  {
    id: "saint",
    name: "saint",
    age: 31,
    occupation: "Site Admin",
    relationship: "Open",
    group: "Admin",
    image: "https://media2.giphy.com/media/v1.Y2lkPTZjMDliOTUyZGEyN3JjOGtjbnFrNDBkdDJsN3IzOG0weGVpd2M3ZmRjMGV5b3kxZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohhwJLZ2P9KOt3Z6w/giphy.gif",
    hook: "Test signal for Crossed Signals.",
    seeking: ["Friends", "Family", "Rivalry"],
    categories: ["friends", "family", "rivals", "open"],
    tags: ["Community Ties", "History", "Bad Decisions", "Anything Goes", "Random Encounters"],
    profile: "https://lowsignal.jcink.net/index.php?showuser=1",
    memberId: 1,
    open: true,
    unknownCaller: true
  },
  {
    id: "spooky",
    name: "Spooky",
    age: 30,
    occupation: "princess",
    relationship: "Single but taken",
    group: "Admin",
    image: "https://64.media.tumblr.com/8da9c79336aeda624a27cfc078fce3f1/8aca44f9746ebd71-ea/s640x960/951a63cafa9fb0440287202dfc1a268e31b60366.gif",
    hook: "the best lil helper",
    seeking: ["Romance", "Friends", "Coworkers"],
    categories: ["romance", "friends", "coworkers", "open"],
    tags: ["Slow Burn", "Found Family", "Bad Decisions", "Long-Term"],
    profile: "https://lowsignal.jcink.net/index.php?showuser=3",
    memberId: 3,
    open: true,
    unknownCaller: true
  },
  {
    id: "itzel-ibarra",
    name: "Itzel Ibarra",
    age: 21,
    occupation: "Personal Assistant",
    relationship: "It's Complicated",
    group: "WhiteNoise",
    image: "https://random.lensdump.com/MWPY1g.gif",
    hook: "it's better to dance with the devil you know than the one you don't.",
    seeking: ["Romance", "Friends", "Rivalry", "Neighbors"],
    categories: ["romance", "friends", "rivals", "neighbors", "open"],
    tags: ["Old Flames", "Community Ties", "Secrets", "History", "Second Chances"],
    profile: "https://lowsignal.jcink.net/index.php?showuser=8",
    memberId: 8,
    open: true,
    unknownCaller: true
  },
  {
    id: "cassius-reed",
    name: "Cassius Reed",
    age: 30,
    occupation: "Fighter",
    relationship: "Single",
    group: "Longwave",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCGVIyOx2ZPCXHauOs7ms2fbkueIHqLtkhFXqDyPYFkw&s=10",
    hook: "Its fine.",
    seeking: ["Romance", "Friends", "Family", "Neighbors"],
    categories: ["romance", "friends", "family", "neighbors"],
    tags: ["Complicated", "Second Chances", "Unexpected Friends", "Secrets"],
    profile: "https://lowsignal.jcink.net/index.php?showuser=9",
    memberId: 9,
    open: false,
    unknownCaller: true
  },

];
